/*
* generated by Xtext
*/
package com.wirywolf.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class UnrealscriptOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
