/*
* generated by Xtext
*/
package com.wirywolf.ui.contentassist;

import com.wirywolf.ui.contentassist.AbstractUnrealscriptProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class UnrealscriptProposalProvider extends AbstractUnrealscriptProposalProvider {

}
