/*
 * generated by Xtext
 */
package com.wirywolf.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class UnrealscriptUiModule extends com.wirywolf.ui.AbstractUnrealscriptUiModule {
	public UnrealscriptUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
